### ISSUE TITLE
Online-Shop-eCommerce-App-Angular-6-Firebase

### ISSUE THREAD

**Issue by MatthewThabo** [AmitXShukla/Online-Shop-eCommerce-App-Angular-6-Firebase#8]
Online-Shop-eCommerce-App-Angular-6-Firebase
Good day,

i am on the first tutorial video for this course and to wards the end when i ng serve it gives me the following error, can you please help

ERROR in ./src/styles.css (./node_modules/css-loader/dist/cjs.js??ref--12-1!./node_modules/postcss-loader/src??embedded!./src/styles.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find '@angular/material/prebuilt-themes/indingo-pink.css'
  in [
    C:\Users\THABO\Desktop\failure\my-app\src
  ]
    at C:\Users\THABO\Desktop\failure\my-app\node_modules\postcss-import\lib\resolve-id.js:35:13
    at async Promise.all (index 0)

**Comment by AmitXShukla** [comment]
1. Look at your angular.json file and please make sure it includes
  "styles": [
              "src/assets/css/styles.css"
            ],
2. Look at your https://github.com/AmitXShukla/Online-Shop-eCommerce-App-Angular-6-Firebase/blob/master/src/assets/css/styles.css file and make sure first line has
@import '~@angular/material/prebuilt-themes/indigo-pink.css';

3. now, finally, go to your node_modules folder and check if this file really exists.
>> node_modules -> @angular/material -> /prebuilt-themes/indingo-pink.css

4. Also check your NodeJS NPM and Angular version

**Comment by MatthewThabo** [comment]
Good day,

1 at my angular.json file it written
 "Style": [
    "src/style.css"

2. Inside the assets folder there's only one file written .gitkeep.

3 node_modules -> @angular/material -> /prebuilt-themes/indingo-pink.css it
does exist

4 style.css file is under app folder and it's written
"@~import/material/prebuilt-themes/indingo-pink.css";

**Comment by AmitXShukla** [comment]
The fact that your assets folder is empty, tells me, you didn't download source code entirely.
Please re-fork or download entire source code in zip file and follow instructions.

If you are doing it for the first time, I suggest to fork below repository instead because it has most recent Angular and Firebase versions and newer video tutorials.

https://github.com/AmitXShukla/ERP-Apps-CRM-Cloud-Angular_Firebase
https://www.youtube.com/playlist?list=PLp0TENYyY8lHNMTAlrfVQKzAvQo3yzHYk
